language: java
addons:
  apt:
    packages:
      ant
before_install:
   - wget --no-check-certificate https://ftp.cixug.es/apache//ant/binaries/apache-ant-1.10.9-bin.tar.gz
   - tar -xzvf apache-ant-1.10.9-bin.tar.gz
   - export PATH=`pwd`/apache-ant-1.10.9/bin:$PATH
   - echo $(ant -version)
   
   